# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:51
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman'), ('Other', 'Other')], default='Male', max_length=8)),
                ('age', models.CharField(choices=[('Under 16', 'Under 16'), ('16-19', '16-19'), ("20's", "20's"), ("30's", "30's"), ("40's", "40's"), ("50's", "50's"), ('60+', '60+')], max_length=8)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('wants_texts', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=40)),
                ('skill', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sportsmanship', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('punctuality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_feedbacks', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
