# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
