# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wants_texts',
            field=models.NullBooleanField(default=True),
        ),
    ]
