# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='small_pic_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
