# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 00:31
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160103_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='<img src="http://res.cloudinary.com/skill-match/image/upload/Man_cqggt4.png"/>', max_length=255, verbose_name='image'),
        ),
    ]
