# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160103_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='small_pic_url',
        ),
    ]
