# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_small_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='small_pic_url',
            field=models.URLField(default='http://res.cloudinary.com/skill-match/image/upload/c_scale,w_50/v1451856958/Man_cqggt4.png', max_length=300),
        ),
    ]
