language: python

python:
  - 3.5.0

services:
  - postgresql

env:
  - DJANGO=1.9

before_install:
  - export SECRET_KEY=$SECRET_KEY
  - export DJANGO_SETTINGS_MODULE=skill_match.travis-settings
  - export PYTHONPATH=$HOME/builds/Skill-Match/skill-match-api
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE skill_match;" -U postgres
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test users matchup api

after_success:
  - coveralls
