# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='court_ranking',
            field=models.IntegerField(null=True),
        ),
    ]
