# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='skill_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
