# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='display_address2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
