# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0002_auto_20151207_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
