# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0002_auto_20151217_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='court_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
