# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0002_auto_20160102_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammenity',
            name='park',
            field=models.ManyToManyField(to='matchup.HendersonPark'),
        ),
    ]
