# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 04:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0003_auto_20151207_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='skill_level',
            field=models.PositiveIntegerField(validators=[(django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100))]),
        ),
    ]
