# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0003_auto_20160102_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hendersonpark',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
