# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0004_auto_20151207_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='skill_level',
            field=models.PositiveIntegerField(),
        ),
    ]
