# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0005_auto_20151207_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(null=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
