# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0005_auto_20160102_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ammenity',
            old_name='park',
            new_name='parks',
        ),
    ]
