# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0006_auto_20160102_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='hendersonpark',
            name='park',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchup.Park'),
        ),
    ]
