# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0007_auto_20151207_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='park',
        ),
    ]
