# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0008_remove_feedback_park'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='title',
        ),
    ]
