# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0009_remove_match_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_completed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_open',
            field=models.NullBooleanField(default=True),
        ),
    ]
