# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0009_auto_20160102_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='num_courts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
