# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0010_auto_20151209_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_confirmed',
            field=models.NullBooleanField(default=False),
        ),
    ]
