# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0010_auto_20160103_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='sport',
            field=models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Pickleball', 'Pickleball'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Pickleball', 'Pickleball'), ('Other', 'Other')], default='Tennis', max_length=25),
        ),
    ]
