# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0011_auto_20160103_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='img_url',
            field=models.URLField(default='http://res.cloudinary.com/skill-match/image/upload/v1451804013/trophy_200_cnaras.jpg'),
        ),
    ]
