# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0012_auto_20151210_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='yelp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
