# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0012_auto_20160103_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='park',
            name='longitude',
        ),
        migrations.AddField(
            model_name='park',
            name='rating_img_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='rating_img_url_small',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='img_url',
            field=models.URLField(default='http://res.cloudinary.com/skill-match/image/upload/v1451804013/trophy_200_cnaras.jpg'),
        ),
    ]
