# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0013_auto_20160103_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='hendersonpark',
            name='string_id',
        ),
    ]
