# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0014_auto_20151210_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='park',
            name='mobile_url',
        ),
        migrations.RemoveField(
            model_name='park',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='park',
            name='review_count',
        ),
    ]
