# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0015_remove_feedback_court_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='player',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
