# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0015_auto_20151211_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='mobile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
