# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0017_auto_20160105_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_succesful',
        ),
    ]
