# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0018_auto_20151211_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
