# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0021_skill_num_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='sportsmanship',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
