# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0023_auto_20151215_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Other', 'Other')], default='Tennis', max_length=25, null=True)),
                ('num_courts', models.IntegerField(null=True)),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchup.Park')),
            ],
        ),
    ]
