# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0025_match_is_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='challenge_declined',
            field=models.NullBooleanField(default=False),
        ),
    ]
