# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0026_match_challenge_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
